from typing import Dict, Tuple

# Map source_id -> (country_code, name, feed_url)
# Structure: {source_id: (country_code, name, feed_url)}
# country_code is used to get translated country name
SOURCES: Dict[int, Tuple[str, str, str]] = {
    # Hungary
    0: ("hu", "telex.hu", "https://telex.hu/rss"),
    1: ("hu", "444.hu", "https://444.hu/feed"),
    2: ("hu", "hvg.hu", "https://hvg.hu/rss"),
    3: ("hu", "magyarnarancs.hu", "https://magyarnarancs.hu/rss"),
    4: ("hu", "24.hu", "https://24.hu/rss"),
    5: ("hu", "hang.hu", "https://hang.hu/feed"),
    6: ("hu", "index.hu", "https://index.hu/24ora/rss/"),
    7: ("hu", "origo.hu", "https://www.origo.hu/contentpartner/rss/origoall/origo.xml"),

    # Germany
    10: ("de", "Abendzeitung RSS Feed", "https://www.abendzeitung-muenchen.de/storage/rss/rss/alle-artikel-abendzeitung.xml"),
    11: ("de", "DER SPIEGEL RSS Feed", "https://www.spiegel.de/international/index.rss"),
    12: ("de", "Frankfurter Allgemeine Zeitung RSS Feed", "https://www.faz.net/rss/aktuell/"),
    13: ("de", "Freie Presse RSS Feed", "https://www.freiepresse.de/rss/rss_chemnitz.php"),
    14: ("de", "General-Anzeiger RSS Feed", "https://ga.de/feed.rss"),
    15: ("de", "German Brief RSS Feed", "https://www.germanbrief.com/blog-feed.xml"),
    16: ("de", "Hamburger Morgenpost RSS Feed", "https://www.mopo.de/feed/"),
    17: ("de", "Handelsblatt RSS Feed", "https://www.handelsblatt.com/contentexport/feed/top-themen"),
    18: ("de", "Hannoversche Allgemeine RSS Feed", "https://www.haz.de/arc/outboundfeeds/rss/"),
    19: ("de", "JUNGE FREIHEIT RSS Feed", "https://jungefreiheit.de/feed/"),
    20: ("de", "Kieler Nachrichten RSS Feed", "https://www.kn-online.de/arc/outboundfeeds/rss/"),
    21: ("de", "Kölner Stadt-Anzeiger RSS Feed", "https://feed.ksta.de/feed/rss/index.rss"),
    22: ("de", "LVZ RSS Feed", "https://www.lvz.de/arc/outboundfeeds/rss/"),
    23: ("de", "Lübecker Nachrichten RSS Feed", "https://www.ln-online.de/arc/outboundfeeds/rss/"),
    24: ("de", "Main-Post RSS Feed", "https://www.mainpost.de/storage/rss/rss/topnews.xml"),
    25: ("de", "Münstersche Zeitung RSS Feed", "https://www.muensterschezeitung.de/rss/feed/mz_lokales"),
    26: ("de", "Oberhessische Presse RSS Feed", "https://www.op-marburg.de/arc/outboundfeeds/rss/"),
    27: ("de", "Ostsee Zeitung RSS Feed", "https://www.ostsee-zeitung.de/arc/outboundfeeds/rss/"),
    28: ("de", "Rheinische Post RSS Feed", "https://rp-online.de/feed.rss"),
    29: ("de", "Ruhr Nachrichten RSS Feed", "https://www.ruhrnachrichten.de/feed/"),
    30: ("de", "Stern RSS Feed", "https://www.stern.de/feed/standard/alle-nachrichten/"),
    31: ("de", "Stuttgart Journal RSS Feed", "https://stuttgart-journal.de/tp3/feed/"),
    32: ("de", "Süddeutsche Zeitung RSS Feed", "https://rss.sueddeutsche.de/rss/Topthemen"),
    33: ("de", "The Local Germany RSS Feed", "https://feeds.thelocal.com/rss/de"),
    34: ("de", "The Munich Eye RSS Feed", "https://themunicheye.com/sitemap.rss"),
    35: ("de", "ZEIT ONLINE RSS Feed", "http://newsfeed.zeit.de/index"),
    36: ("de", "deutschland.de RSS Feed", "https://www.deutschland.de/en/feed-news/rss.xml"),
    37: ("de", "junge Welt RSS Feed", "https://www.jungewelt.de/feeds/newsticker.rss"),
    38: ("de", "neues deutschland RSS Feed", "https://www.nd-aktuell.de/rss/aktuell.php"),
    39: ("de", "taz RSS Feed", "https://taz.de/!p4608;rss/"),
    40: ("de", "Deutschlandfunk Kultur Bücher", "https://www.deutschlandfunkkultur.de/buecher-108.rss"),
    41: ("de", "Deutschlandfunk Kultur Politik", "https://www.deutschlandfunkkultur.de/politik-114.rss"),
    42: ("de", "Deutschlandfunk Nachrichten", "https://www.deutschlandfunk.de/nachrichten-100.rss"),
    43: ("de", "Deutschlandfunk Politik", "https://www.deutschlandfunk.de/politikportal-100.rss"),
    44: ("de", "Deutschlandfunk Wirtschaft", "https://www.deutschlandfunk.de/wirtschaft-106.rss"),
    45: ("de", "Deutschlandfunk Wissen", "https://www.deutschlandfunk.de/wissen-106.rss"),
    46: ("de", "IamExpat.de", "https://www.iamexpat.de/feed"),
    47: ("de", "ZEIT ONLINE", "https://newsfeed.zeit.de/index"),
    48: ("de", "heise online News", "https://www.heise.de/rss/heise-atom.xml"),

    # France
    20: ("fr", "20 Minutes RSS Feed", "https://www.20minutes.fr/feeds/rss-une.xml"),
    21: ("fr", "Arab News » France RSS Feed", "https://www.arabnews.com/taxonomy/term/1516/feed"),
    22: ("fr", "Atlantic Council » France RSS Feed", "https://www.atlanticcouncil.org/region/france/feed"),
    23: ("fr", "Baltic News Network » France RSS Feed", "https://bnn-news.com/tag/france/feed"),
    24: ("fr", "Channel 4 News » France RSS Feed", "https://www.channel4.com/news/world/france/feed"),
    25: ("fr", "Expatica France RSS Feed", "https://www.expatica.com/fr/feed/"),
    26: ("fr", "Financial Times » France RSS Feed", "https://www.ft.com/france?format=rss"),
    27: ("fr", "Foreign Affairs » France RSS Feed", "https://www.foreignaffairs.com/feeds/region/France/rss.xml"),
    28: ("fr", "France 24 RSS Feed", "https://www.france24.com/en/rss"),
    29: ("fr", "France Diplomacy RSS Feed", "https://www.diplomatie.gouv.fr/spip.php?page=backend-fd"),
    30: ("fr", "France Soir RSS Feed", "https://www.francesoir.fr/rss.xml"),
    31: ("fr", "France Today RSS Feed", "https://francetoday.com/feed"),
    32: ("fr", "FrenchDailyNews RSS Feed", "https://frenchdailynews.com/feed"),
    33: ("fr", "InfoMigrants RSS Feed", "https://www.infomigrants.net/en/rss/all.xml"),
    34: ("fr", "L\'Est Républicain RSS Feed", "https://www.estrepublicain.fr/rss"),
    35: ("fr", "La Croix RSS Feed", "https://www.la-croix.com/feeds/rss/site.xml"),
    36: ("fr", "La Dépêche RSS Feed", "https://www.ladepeche.fr/rss.xml"),
    37: ("fr", "La France Agricole RSS Feed", "https://www.lafranceagricole.fr/rss"),
    38: ("fr", "Le HuffPost RSS Feed", "https://www.huffingtonpost.fr/rss/all_headline.xml"),
    39: ("fr", "Le Monde RSS Feed", "https://www.lemonde.fr/en/rss/une.xml"),
    40: ("fr", "Le Monde diplomatique RSS Feed", "https://mondediplo.com/backend"),
    41: ("fr", "Le Nouvel Obs RSS Feed", "https://www.nouvelobs.com/a-la-une/rss.xml"),
    42: ("fr", "Le Point RSS Feed", "https://www.lepoint.fr/24h-infos/rss.xml"),
    43: ("fr", "Les Dernières Nouvelles d\'Alsace RSS Feed", "https://www.dna.fr/rss"),
    44: ("fr", "Marienne RSS Feed", "https://www.marianne.net/rss.xml"),
    45: ("fr", "Mediapart RSS Feed", "https://www.mediapart.fr/articles/feed"),
    46: ("fr", "Midi Libre RSS Feed", "https://www.midilibre.fr/rss.xml"),
    47: ("fr", "Moroccan World News » France RSS Feed", "https://www.moroccoworldnews.com/tag/france/feed"),
    48: ("fr", "Ouest-France RSS Feed", "https://www.ouest-france.fr/rss/une"),
    49: ("fr", "RFI RSS Feed", "https://www.rfi.fr/en/rss"),
    50: ("fr", "RFI RSS Feed (France)", "https://www.rfi.fr/en/france/rss"),
    51: ("fr", "Sud Ouest RSS Feed", "https://www.sudouest.fr/essentiel/rss.xml"),
    52: ("fr", "TechCrunch » France RSS Feed", "https://techcrunch.com/tag/france/feed/"),
    53: ("fr", "The Conversation » France RSS Feed", "https://theconversation.com/topics/the-conversation-france-24313/articles.atom"),
    54: ("fr", "The Independent » France RSS Feed", "https://www.the-independent.com/topic/france/rss"),
    55: ("fr", "The Local France RSS Feed", "https://feeds.thelocal.com/rss/builder/fr"),
    56: ("fr", "The Local RSS Feed", "https://feeds.thelocal.com/rss/fr"),
    57: ("fr", "The New York Times » France RSS Feed", "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/topic/destination/france/rss.xml"),
    58: ("fr", "The Paris News RSS Feed", "https://theparisnews.com/search/?q=&t=article&l=10&d=&d1=&d2=&s=start_time&sd=desc&c%5B%5D=news&f=rss"),
    59: ("fr", "The Paris Star RSS Feed", "https://www.parisstaronline.com/feed"),
    60: ("fr", "U.S. News & World Report » France RSS Feed", "https://www.usnews.com/topics/locations/france/rss"),
    61: ("fr", "Yahoo Actualités RSS Feed", "https://fr.news.yahoo.com/rss"),
    62: ("fr", "France 24", "https://www.france24.com/fr/rss"),
    63: ("fr", "France 24 Europe", "https://www.france24.com/en/europe/rss"),
    64: ("fr", "France Diplomacy", "https://www.diplomatie.gouv.fr/spip.php?page=rss"),
    65: ("fr", "France Today", "https://www.francetoday.com/feed"),
    66: ("fr", "Le Monde", "https://www.lemonde.fr/rss/une.xml"),
    67: ("fr", "RFI France", "https://www.rfi.fr/fr/france/rss"),

    # United Kingdom
    30: ("uk", "Breaking News Today RSS Feed", "https://www.breakingnewstoday.co.uk/feed/"),
    31: ("uk", "BreakingNews.ie RSS Feed", "https://feeds.breakingnews.ie/bntopstories"),
    32: ("uk", "Daily Echo RSS Feed", "https://www.dailyecho.co.uk/news/rss/"),
    33: ("uk", "Daily Politics RSS Feed", "https://www.dailypolitics.com/feed.xml"),
    34: ("uk", "HuffPost UK RSS Feed", "https://www.huffingtonpost.co.uk/feeds/index.xml"),
    35: ("uk", "KentNews.Online RSS Feed", "https://www.kentnews.online/feed/"),
    36: ("uk", "Newsnet.scot RSS Feed", "https://newsnet.scot/feed/"),
    37: ("uk", "Northern Ireland World RSS Feed", "https://www.northernirelandworld.com/news/rss"),
    38: ("uk", "Scottish Field RSS Feed", "https://www.scottishfield.co.uk/feed/"),
    39: ("uk", "The Church of England Newspaper RSS Feed", "https://www.churchnewspaper.com/feed/"),
    40: ("uk", "The Daily Mash RSS Feed", "https://www.thedailymash.co.uk/feed"),
    41: ("uk", "The Guardian » UK RSS Feed", "https://www.theguardian.com/uk-news/rss"),
    42: ("uk", "The Scotsman » News RSS Feed", "https://www.scotsman.com/news/rss"),
    43: ("uk", "The Scottish Sun » Liverpool FC RSS Feed", "https://www.thescottishsun.co.uk/feed/"),

    # United States
    150: ("us", "7News Boston RSS Feed", "https://whdh.com/feed/"),
    151: ("us", "ABC13 Houston RSS Feed", "https://abc13.com/feed/"),
    152: ("us", "ABC7 San Francisco RSS Feed", "https://abc7news.com/feed/"),
    153: ("us", "Billy Penn RSS Feed", "https://billypenn.com/feed/"),
    154: ("us", "Boston.com RSS Feed", "https://www.boston.com/feed/"),
    155: ("us", "CBS News RSS Feed (DC)", "https://www.cbsnews.com/latest/rss/main"),
    156: ("us", "Chamberlainsun RSS Feed", "https://chamberlainsun.com/feed/"),
    157: ("us", "City Limits RSS Feed", "https://citylimits.org/feed/"),
    158: ("us", "Daily Herald RSS Feed", "https://www.dailyherald.com/rssfeed/top-stories/"),
    159: ("us", "Denver Westword RSS Feed", "https://www.westword.com/denver/Rss.xml"),
    160: ("us", "Detroit Metro Times RSS Feed", "https://www.metrotimes.com/detroit/Rss.xml"),
    161: ("us", "FOX31 Denver KDVR RSS Feed", "https://kdvr.com/feed/"),
    162: ("us", "FOX5 KUSI NEWS RSS Feed", "https://fox5sandiego.com/feed/"),
    163: ("us", "Forest Hills Times RSS Feed", "https://foresthillstimes.com/feed/"),
    164: ("us", "Fox2Now RSS Feed", "https://fox2now.com/feed/"),
    165: ("us", "Foxton News RSS Feed", "https://foxtonnews.com/feed/"),
    166: ("us", "Heartland Newsfeed RSS Feed", "https://www.heartlandnewsfeed.com/feed/"),
    167: ("us", "Houston Press RSS Feed", "https://www.houstonpress.com/houston/Rss.xml"),
    168: ("us", "KRON4 RSS Feed", "https://www.kron4.com/feed/"),
    169: ("us", "KTLA RSS Feed", "https://ktla.com/feed/"),
    170: ("us", "KXAN News RSS Feed", "https://www.kxan.com/feed/"),
    171: ("us", "LA Observed RSS Feed", "http://www.laobserved.com/index.rdf"),
    172: ("us", "Miami Today RSS Feed", "https://www.miamitodaynews.com/feed/"),
    173: ("us", "MinnPost RSS Feed", "https://www.minnpost.com/feed/"),
    174: ("us", "NBC 5 Dallas-Fort Worth RSS Feed", "https://www.nbcdfw.com/news/feed/"),
    175: ("us", "NBC 6 South Florida RSS Feed", "https://www.nbcmiami.com/?rss=y"),
    176: ("us", "NBC 7 San Diego RSS Feed", "https://www.nbcsandiego.com/?rss=y"),
    177: ("us", "NBC Chicago RSS Feed", "https://www.nbcchicago.com/?rss=y"),
    178: ("us", "NBC Los Angeles RSS Feed", "https://www.nbclosangeles.com/?rss=y"),
    179: ("us", "NBC10 Philadelphia RSS Feed", "https://www.nbcphiladelphia.com/?rss=y"),
    180: ("us", "NBC4 Washington RSS Feed", "https://www.nbcwashington.com/?rss=y"),
    181: ("us", "NEWS10 ABC RSS Feed", "https://www.news10.com/feed/"),
    182: ("us", "New York Daily News RSS Feed", "https://www.nydailynews.com/feed/"),
    183: ("us", "PhillyVoice RSS Feed", "https://www.phillyvoice.com/feed/"),
    184: ("us", "Pioneer Press RSS Feed", "https://www.twincities.com/feed/"),
    185: ("us", "Riverfront Times RSS Feed", "https://www.riverfronttimes.com/stlouis/Rss.xml"),
    186: ("us", "SeattlePI RSS Feed", "https://www.seattlepi.com/local/feed/seattlepi-com-Local-News-218.php"),
    187: ("us", "The Denver Post RSS Feed", "https://www.denverpost.com/feed/"),
    188: ("us", "The Published Reporter RSS Feed", "https://www.publishedreporter.com/feed/"),
    189: ("us", "The Texas Observer RSS Feed", "https://www.texasobserver.org/feed/"),
    190: ("us", "The Village Voice RSS Feed", "https://www.villagevoice.com/feed/"),
    191: ("us", "Times of San Diego RSS Feed", "https://timesofsandiego.com/feed/"),
    192: ("us", "US Top Stories RSS Feed", "https://ustopstories.com/feed/"),
    193: ("us", "WFLA News Channel 8 RSS Feed", "https://www.wfla.com/feed/"),
    194: ("us", "WGN-TV RSS Feed", "https://wgntv.com/feed/"),
    195: ("us", "WIVB-TV RSS Feed", "https://www.wivb.com/feed/"),
    196: ("us", "WSVN 7 News Miami RSS Feed", "https://wsvn.com/feed/"),
    197: ("us", "WTOP RSS Feed", "https://wtop.com/feed/"),

    # Italy
    40: ("it", "La Repubblica", "https://www.repubblica.it/rss/homepage/rss2.0.xml"),
    41: ("it", "Corriere della Sera", "https://xml2.corriereobjects.it/rss/homepage.xml"),
    42: ("it", "La Stampa", "https://www.lastampa.it/rss.xml"),
    43: ("it", "Il Sole 24 Ore", "https://www.ilsole24ore.com/rss/home.xml"),
    44: ("it", "ANSA", "https://www.ansa.it/sito/ansait_rss.xml"),

    # Spain
    50: ("es", "Costa News RSS Feed", "https://www.costa-news.com/feed/"),
    51: ("es", "EL PAÍS RSS Feed", "https://feeds.elpais.com/mrss-s/pages/ep/site/english.elpais.com/portada"),
    52: ("es", "El Diario NY RSS Feed", "https://eldiariony.com/feed/"),
    53: ("es", "El Diario RSS Feed", "https://www.eldiario.es/rss"),
    54: ("es", "Elmundo RSS Feed", "https://e00-elmundo.uecdn.es/rss/portada.xml"),
    55: ("es", "Euro Weekly News RSS Feed", "https://euroweeklynews.com/feed/"),
    56: ("es", "Madrid Metropolitan RSS Feed", "https://www.madridmetropolitan.com/feed/"),
    57: ("es", "Majorca Daily Bulletin RSS Feed", "https://www.majorcadailybulletin.com/feed.rss"),
    58: ("es", "Seaside Gazette RSS Feed", "https://www.theseasidegazette.com/feed/"),
    59: ("es", "Tenerife News RSS Feed", "https://www.tenerifenews.com/feed/"),
    60: ("es", "The Canary News RSS Feed", "https://thecanarynews.com/feed/"),
    61: ("es", "The Leader Newspaper RSS Feed", "https://theleader.info/feed/"),
    62: ("es", "The Local Spain RSS Feed", "https://feeds.thelocal.com/rss/es"),
    63: ("es", "The Olive Press RSS Feed", "https://www.theolivepress.es/feed/"),
    64: ("es", "The Resident RSS Feed", "http://theresident.eu/feed/"),
    65: ("es", "Valencia International RSS Feed", "https://valencia-international.com/feed/"),
    66: ("es", "Valencian RSS Feed", "https://valencian.es/feed/"),

    # Poland
    60: ("pl", "Dziennik Wschodni RSS Feed", "https://www.dziennikwschodni.pl/rss"),
    61: ("pl", "Fakt.pl RSS Feed", "https://www.fakt.pl/rss"),
    62: ("pl", "Gazeta Krakowska RSS Feed", "https://gazetakrakowska.pl/rss/gazetakrakowska.xml"),
    63: ("pl", "Głos Wielkopolski RSS Feed", "https://gloswielkopolski.pl/rss/gloswielkopolski.xml"),
    64: ("pl", "Kurier Poranny RSS Feed", "https://poranny.pl/rss/kurierporanny.xml"),
    65: ("pl", "Notes From Poland RSS Feed", "https://notesfrompoland.com/feed/"),
    66: ("pl", "Nowa Trybuna Opolska RSS Feed", "https://nto.pl/rss/nowatrybunaopolska.xml"),
    67: ("pl", "Nowy Dziennik RSS Feed", "https://dziennik.com/feed/"),
    68: ("pl", "Rzeczpospolita RSS Feed", "https://www.rp.pl/rss_main?unknown-old-rss"),
    69: ("pl", "Warsaw Insider RSS Feed", "https://warsawinsider.pl/feed/"),
    70: ("pl", "Wyborcza.pl RSS Feed", "https://wyborcza.pl/pub/rss/najnowsze_wyborcza.xml"),
    71: ("pl", "Życie Warszawy RSS Feed", "https://www.zw.com.pl/rss/1.html"),

    # Austria
    70: ("at", "Der Ennstaler RSS Feed", "https://www.derennstaler.at/rss.xml"),
    71: ("at", "Die Presse RSS Feed", "https://www.diepresse.com/rss//"),
    72: ("at", "Kronen Zeitung RSS Feed", "https://api.krone.at/v1/rss/rssfeed-google.xml?id=2311992"),
    73: ("at", "NÖN RSS Feed", "https://www.noen.at/xml/rss"),
    74: ("at", "OTS RSS Feed", "https://www.ots.at/rss/index"),
    75: ("at", "OÖNachrichten RSS Feed", "https://www.nachrichten.at/storage/rss/rss/nachrichten.xml"),
    76: ("at", "Salzburger Nachrichten RSS Feed", "https://www.sn.at/xml/rss"),
    77: ("at", "Yeni Vatan Gazetesi RSS Feed", "https://www.yenivatan.at/feed/"),
    78: ("at", "Brutkasten - Startups/Business", "https://brutkasten.com/feed"),
    79: ("at", "Der Standard", "https://derstandard.at/rss"),
    80: ("at", "Die Presse", "https://diepresse.com/rss"),
    81: ("at", "Kronen Zeitung (Krone.at)", "https://api.krone.at/v1/rss/rssfeed-1"),
    82: ("at", "Kurier", "https://kurier.at/rss"),
    83: ("at", "ORF.at Nachrichten", "https://orf.at/rss/"),
    84: ("at", "Oberösterreichische Nachrichten (OÖNachrichten)", "https://nachrichten.at/storage/rss/rss.xml"),
    85: ("at", "Trend (Wirtschaft)", "https://trend.at/.content/rss/feed.xml"),
    86: ("at", "Vienna Online", "https://www.vienna.at/feed"),
    87: ("at", "Wiener Zeitung", "https://wienerzeitung.at/_wzo/rss"),

    # Slovenia
    80: ("si", "Delo", "https://www.delo.si/rss"),
    81: ("si", "Dnevnik", "https://www.dnevnik.si/rss"),
    82: ("si", "RTV Slovenija", "https://www.rtvslo.si/rss"),
    83: ("si", "Večer", "https://www.vecer.com/rss"),

    # Switzerland
    90: ("ch", "Neue Zürcher Zeitung", "https://www.nzz.ch/rss"),
    91: ("ch", "Tages-Anzeiger", "https://www.tagesanzeiger.ch/rss.html"),
    92: ("ch", "Le Temps", "https://www.letemps.ch/rss"),
    93: ("ch", "Swissinfo", "https://www.swissinfo.ch/eng/rss"),
    94: ("ch", "Blick", "https://www.blick.ch/rss"),

    # Czech Republic
    100: ("cz", "iDNES.cz", "https://servis.idnes.cz/rss.aspx"),
    101: ("cz", "Novinky.cz", "https://www.novinky.cz/rss"),
    102: ("cz", "Lidovky.cz", "https://www.lidovky.cz/rss.aspx"),
    103: ("cz", "Česká televize", "https://www.ceskatelevize.cz/ct24/rss"),
    104: ("cz", "Aktuálně.cz", "https://zpravy.aktualne.cz/rss/"),

    # Slovakia
    110: ("sk", "SME.sk", "https://www.sme.sk/rss-title"),
    111: ("sk", "Pravda.sk", "https://www.pravda.sk/rss"),
    112: ("sk", "Aktuality.sk", "https://www.aktuality.sk/rss"),
    113: ("sk", "Denník N", "https://dennikn.sk/rss"),
    114: ("sk", "HNonline.sk", "https://www.hnonline.sk/rss"),

    # Romania
    120: ("ro", "Adevărul", "https://adevarul.ro/rss"),
    121: ("ro", "Gândul", "https://www.gandul.ro/rss"),
    122: ("ro", "HotNews.ro", "https://www.hotnews.ro/rss"),
    123: ("ro", "Digi24", "https://www.digi24.ro/rss"),
    124: ("ro", "Realitatea.net", "https://www.realitatea.net/rss"),

    # Croatia
    130: ("hr", "Jutarnji List", "https://www.jutarnji.hr/rss"),
    131: ("hr", "Večernji List", "https://www.vecernji.hr/rss"),
    132: ("hr", "24sata", "https://www.24sata.hr/rss"),
    133: ("hr", "Index.hr", "https://www.index.hr/rss"),
    134: ("hr", "HRT", "https://vijesti.hrt.hr/rss"),

    # Serbia
    140: ("rs", "Blic", "https://www.blic.rs/rss"),
    141: ("rs", "Večernje Novosti", "https://www.novosti.rs/rss"),
    142: ("rs", "Danas", "https://www.danas.rs/rss"),
    143: ("rs", "RTS", "https://www.rts.rs/page/rss/sr.html"),
    144: ("rs", "Politika", "https://www.politika.rs/rss"),

    # Retro Gaming
    200: ("retro", "AUSRETROGAMER", "http://feeds.feedburner.com/ausretrogamer"),
    201: ("retro", "Arcade Attack", "https://www.arcadeattack.co.uk/feed"),
    202: ("retro", "Arcade Blogger", "https://arcadeblogger.com/feed"),
    203: ("retro", "Classic-Games.net", "https://classic-games.net/feed"),
    204: ("retro", "FRGCB - Finnish Retro Game Comparison Blog", "https://frgcb.blogspot.com/feeds/posts/default"),
    205: ("retro", "Indie Retro News", "https://www.indieretronews.com/feeds/posts/default"),
    206: ("retro", "Infinity Retro", "https://infinityretro.com/feed"),
    207: ("retro", "RF Generation Retro Gaming News", "https://rfgeneration.com/news/blog.rss"),
    208: ("retro", "Retro Game Corps", "https://retrogamecorps.com/feed"),
    209: ("retro", "Retro Gaming Discussion Show (RGDS)", "https://retrogamingdailyshow.libsyn.com/rss"),
    210: ("retro", "Retro Garden", "https://retrogarden.co.uk/feed"),
    211: ("retro", "Retro vGames Blog", "https://retrovgames.com/feed"),
    212: ("retro", "RetroAchievements", "https://retroachievements.org/rss/feed.php"),
    213: ("retro", "Retronauts", "https://www.retronauts.com/feed"),
    214: ("retro", "Vintage Computing and Gaming", "https://www.vintagecomputing.com/index.php/feed"),
    215: ("retro", "Vintage is the New Old", "https://vintageisthenewold.com/feed"),

}
